version: '3'
services:
  web:
    image: iimog/bcdatabaser_web
    ports:
      - "3000:3000"
    links:
      - redis
    volumes:
      - ./.zenodo_token:/bcdatabaser/bcdatabaser/.zenodo_token
      - ./.env:/bcdatabaser/.env

  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes

